LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Amber
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Amber/AmberThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Black
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Black/BlackThemeOverlay
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Blue
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Blue/BlueThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := BlueGray
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/BlueGray/BlueGrayThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := BlueSky
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/BlueSky/BlueSkyThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Brown
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Brown/BrownThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Cyan
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Cyan/CyanThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := DarkBlue
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/DarkBlue/DarkBlueThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := DeepGray
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/DeepGray/DeepGrayThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := DeepOrange
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/DeepOrange/DeepOrangeThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Gray
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Gray/GrayThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Indigo
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Indigo/IndigoThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := LightGreen
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/LightGreen/LightGreenThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Orange
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Orange/Orange.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Pink
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Pink/PinkThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Pixel
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Pixel/PixelThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Purple
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Purple/PurpleThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Red
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Red/RedThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Teal
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Teal/TealThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := Yellow
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES :=  prebuilt/system/Yellow/YellowThemeOverlay.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/vendor/overlay/
include $(BUILD_PREBUILT) 

